#!/bin/sh

RLOCATE_GROUP=rlocate
RLOCATE_DIR=/var/lib/rlocate

set -e
suffix=notrlocate
#if [ purge = "$1" ]; then
#        rm -rf /etc/rlocate/
#fi
if [ remove = "$1" ]; then
	dpkg-divert --package rlocate --remove --rename \
		--divert /usr/bin/locate.$suffix \
			/usr/bin/locate
	dpkg-divert --package rlocate --remove --rename \
		--divert /usr/bin/updatedb.$suffix \
			/usr/bin/updatedb
	dpkg-divert --package rlocate --remove --rename \
		--divert /usr/share/man/man1/locate.$suffix.1.gz \
			/usr/share/man/man1/locate.1.gz
	dpkg-divert --package rlocate --remove --rename \
		--divert /usr/share/man/man1/updatedb.$suffix.1.gz \
			/usr/share/man/man1/updatedb.1.gz
	dpkg-divert --package rlocate --remove --rename \
		--divert /etc/cron.daily/find.$suffix \
			/etc/cron.daily/find

	delgroup $RLOCATE_GROUP
fi


#DEBHELPER#
